### ISSUE TITLE
Advanced Library search

### ISSUE THREAD

**Issue by JorgeRuizDev** [JorgeRuizDev/MySpotifyFM#8]
- [x] **Allow the creation of a new playlist based on the results.** 

Filter user's library by:

- [x] Generic Text (Song Name, artist, genre, etc)

Or use advanced filters:

- [x] Year Interval
- [x]  Fixed Year
- [x]  Decade (LastFM as it is the most reliable date source)
- [x]  Artist
- [x]  Genre (Spotify + LastFM)
- [x]  Album Name
- [x]  Popularity
